### ISSUE TITLE
Fix deploy to PyPI

### ISSUE THREAD

**Issue by griff-rees** [Living-with-machines/alto2txt#53]
While commit #51 and release [v.0.3.4](https://github.com/Living-with-machines/alto2txt/releases/latest) build for [`TestPyPI`](https://github.com/Living-with-machines/alto2txt/actions/workflows/deploy-to-testpypi.yml), they currently fail for [`PyPI`](https://github.com/Living-with-machines/alto2txt/actions/workflows/deploy-to-pypi.yml).

**Comment by griff-rees** [comment]
`pkginfo.distribution` error:
```Traceback (most recent call last):
  File "/usr/local/bin/twine", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/twine/__main__.py", line 33, in main
    error = cli.dispatch(sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/twine/cli.py", line 123, in dispatch
    return main(args.args)
  File "/usr/local/lib/python3.9/site-packages/twine/commands/check.py", line 183, in main
    return check(parsed_args.dists, strict=parsed_args.strict)
  File "/usr/local/lib/python3.9/site-packages/twine/commands/check.py", line 129, in check
    warnings, is_ok = _check_file(filename, render_warning_stream)
  File "/usr/local/lib/python3.9/site-packages/twine/commands/check.py", line 73, in _check_file
    package = package_file.PackageFile.from_filename(filename, comment=None)
  File "/usr/local/lib/python3.9/site-packages/twine/package.py", line 96, in from_filename
    meta = DIST_TYPES[dtype](filename)
  File "/usr/local/lib/python3.9/site-packages/twine/wheel.py", line 42, in __init__
    self.extractMetadata()
  File "/usr/local/lib/python3.9/site-packages/pkginfo/distribution.py", line 121, in extractMetadata
    self.parse(data)
  File "/usr/local/lib/python3.9/site-packages/twine/wheel.py", line 89, in parse
    fp = io.StringIO(distribution.must_decode(data))
AttributeError: module 'pkginfo.distribution' has no attribute 'must_decode'
Checking dist/alto2txt-0.3.4-py3-none-any.whl: 
##[debug]Docker Action run completed with exit code 1
##[debug]Finishing: Publish tagged build to PyPI
```
